name: Deploy to Server

on:
  push:
    branches:
      - master # 這裡使用你的主要分支名稱，可以根據實際情況修改

jobs:
  deploy:
    runs-on: ubuntu-22.04 # ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 # 使用官方的Checkout action來檢出你的代碼

      - name: Yarn Install & Build
        run: yarn install && yarn build

      - name: Zip the Dist Folder
        run: rm -f dist.zip && zip -r dist.zip dist/

      - name: Deploy to Server
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.pem
          chmod 600 ~/.ssh/staging.pem
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.pem
            StrictHostKeyChecking no
          END
          scp -i $SSH_KEY dist.zip $SSH_USER@$SSH_HOST:/var/www/html/
          ssh -i $SSH_KEY $SSH_USER@$SSH_HOST "cd /var/www/html/ && rm -rf dist && unzip dist.zip"
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
